### ISSUE TITLE
Erstellen von Formular und der Aufgabenliste 

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-user-stories#1]
Value Proposition

Als Benutzer 
Ich brauche eine Eingabefeld und einen Button der meine aufgaben in eine Aufgabenliste erstellt. 
Damit ich meinen Tag plannen kann. 

## Description

<img width="190" alt="Todo" src="https://user-images.githubusercontent.com/104771076/180177312-fa8f22c1-00e7-40a4-a8d0-55c3c49f1327.png">

## Acceptance Criteria

- [ ] Es gibt ein Eingabefeld, da kann man seine Aufgaben eingeben. 
- [ ] mit dem Submit button wird die aufgabe in die Liste hinzugefügt. 
- [ ] Die Aufgabe erscheint in der Liste und wird Rot markiert. 
- [ ] Am ende der aufgabe ist ein Button der eine Lüschfunktion hat. 

## Tasks

(for developers team)

- [ ] Components erstellen Todo.js und TodoList.js
- [ ] Erstellung des Formulars,(Überschrift, Eingabefeld, Button(Submit und Löschbutton)) 
- [ ] die Button werden in Storybook erstellt.
- [ ] Liste wird erstelt eine <ul>
- [ ] stayles, positionierung der Elemente

**Comment by actyvystom** [comment]
Hi Milan,

this is a good start for a first user story!
Though a few thoughts to consider:
 
try to be more precise in your wording of tasks and acceptance criteria, e.g. you mention "Aufgabe" as a (text) value to be entered in the input field, and then it is added to the list of todos/tasks - I guess you should change the wording a little bit, as it is not the task itself, which will be displayed in the list, but a (list) element holding the text of the task and also a button which allows the user to delete the task/todo.

May sound a bit picky, but the clearer your descriptions, the easier to understand for you later and also for all other people reviewing or working with your user stories in the future :nerd_face:

**Comment by Mitrovic-Milan** [comment]
Thank you for looking at my user story and making an informed comment. 
I will take your comments into consideration and hope that you will like my new user story better.

**Comment by PReichetanz** [comment]
Hi Milan,

looks good to me!

Just three minor points:

- You don't need the second line "Offene Todos: 1" now, because you have not yet implemented the functionality to count the todos and display the current value.
- The "X"-Buttons are not mentioned anywhere - if they are meant to delete the todos, I think this should be another user story.
- So far, the user cannot make a todo item change the color from red to green, so your wireframe should only contain red items.

**Comment by Mitrovic-Milan** [comment]
Hi Paul,

thanks for looking at my user story and for the good comments. 
I have responded to your comments and hope they fit your idea

**Comment by PReichetanz** [comment]
Hi Milan,
the only thing left is the acceptance criteria "Das Input-Feld ist (not) required", depending on how you want to handle the input. If you have added this, I would say you are ready to go 🎉

**Comment by chris-yooo** [comment]
after changes from paul think this is a good start :)
