### ISSUE TITLE
Der Countdown zähler 

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-user-stories#2]
Value Proposition

Als Benutzer
brauche ich einen Countdown 
um in der Lage zu sein das ich einen schnellen übersicht habe wie viele offene todos ich habe

## Description
<img width="190" alt="Todo" src="https://user-images.githubusercontent.com/104771076/180197474-baad5efe-b4f4-4b33-a368-6f3efb37ff74.png">

## Acceptance Criteria

- [ ] Bei jedem neuen Todo erhöht sich der Countdown 
- [ ] Bei jedem erledigten Todo zählt der Countdown nach unten selbst wen das Todo noch nicht entvernt worden ist. 
- [ ] Jedes todo wen es in die Liste erstelt worden ist, wird rot makiert beim erledigen der Aufgabe, tippt man aud die erledigte aufgabe und die aufgabe wird grün Markiert. 
- [ ] Wenn man merkt man hat die aufgabe dochnicht erlädiegt wird tippt man wieder auf die aufgabe und die aufgabe wird wieder Rot markiert. 

## Tasks

- [ ] implemintierung eines Countdown
- [ ] Das markieren der Aufgaben und das wechseln von den aufgaben von rot auf grün und von grün auf rot

**Comment by actyvystom** [comment]
Hi Milan, 
also a nice one, too :)

A few comments on this: 
- I doubt that a countdown is a good way to describe this scenario - imho I guess you will have a (mocked) data set of your todos, and each todo will probably have an attribute which indicates its status, e.g. 'done' or 'open', right?
  - so you could get the count information by traversing your todos and counting open ones and done todos  
 - You do not mention the delete functionality neither in your acceptance criteria nor does it show up in the wireframe - maybe better to create another user story for deleting todos
 - Think of adding tests and storybook components in your task list (the todo list element is also part of your first user story, maybe you better add them there)

**Comment by Mitrovic-Milan** [comment]
Hello Thomas, 

thank you for taking the time to read my second User Story. I have completely rewritten the user story and hope that it is okay for you.
